[target.riscv32imac-unknown-none-elf]
runner = ".cargo/cynthion.sh"
#runner = "riscv64-unknown-elf-gdb -q -x .cargo/openocd.gdb"
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "riscv32imac-unknown-none-elf"
